---
title: "Lesson Plan"
description: ""
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Weekly Lesson Plan

-------------------------------------------------------------------------------------------------------------------------
Week Date    Topic 	                                                                                   Remarks
---- ------- ----------------------------------------------------------------------------------------- -------------------------
1    16/08   [Lesson 1: Introduction to GIS for Urban Planning](outline/lesson01_outline.html)
 
2    23/08   [Lesson 2: The Evil is in The Data](outline/lesson02_outline.html) 	

3    30/08   [Lesson 3: Modelling Urban World](outline/lesson03_outline.html) 	

4    06/09   [Lesson 4: Mapping and Visualising Urban World with GIS](outline/lesson04_outline.html)                                     Take-home Exercise 1 due	

5    13/09   [Lesson 5: Vector-based GeoProcessing and GIS Analysis](outline/lesson05_outline.html) 	

6    20/09   [Lesson 6: Urban Applications of Vector-based GIS Analysis](outline/lesson06_outline.html) 	

7    27/09   [Lesson 7: The Science of Mapthematics](outline/lesson07_outline.html)                                                      Take-home Exercise 2 due

8    04/10   Mid-term [Workshop](workshop/workshop.html) 	

9    11/10   [Lesson 8: Urban Applications of Raster-based GIS Analysis](outline/lesson08_outline.html) 	

10   18/10   [Lesson 9: GIS Modelling for Urban Planning Support](outline/lesson09_outline.html) 	                  

11   25/10   [Lesson 10: Urban Network Analysis with GIS](outline/lesson10_outline.html) 

12   01/11   [Lesson 11: Sharing Geographical Information](outline/lesson11_outline.html)  	                                                 Take-home Exercise 3 due

13   08/11   Lesson 12: Epilogue 	

14   15/11	 Poster Presentation                                                                       GIS Project due

15   22/11   Exam week 	
------------------------------------------------------------------------------------------------------------------------



