---
title: "Lesson 2: The Evil is in The Data"
description: |
  A new article created using the Distill format.
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Content

- Representing Real World Geography
    - Digital representation
    - The fundamental problem
    - The spatial data models
    - Topology data models
- Georeferencing
    - Basic concepts of projections and coordinates
    - Georeferencing
    - Geocoding
- Geospatial data modelling
    - Geospatial database design
    - Spatial Metadata
    - Spatial indexing
    - Multi-user editing and versioning
- Geospatial Data Repositories
    - File-based
    - Geospatial RDBMS
    - Cloud based geospatial database

## Lesson Slides and Hands-on Notes 

- Lesson slide in [html](lesson/lesson01/lesson01.html) and [pdf](lesson/lesson01/lesson01.pdf) formats
- Hands-on Exercise in [html]() format.

## Readings
### Core Readings

- [Chapter 2 Feature Representation](https://mgimond.github.io/Spatial/chp02-0.html) of Intro to GIS and Spatial Analysis
- [Chapter 3 GIS Data Management](https://mgimond.github.io/Spatial/gis-data-management.html) of Intro to GIS and Spatial Analysis
- [Chapter 9 Coordinate Systems](https://mgimond.github.io/Spatial/chp09-0.html) of Intro to GIS and Spatial Analysis
- [Modeling Our World: The ESRI Guide to Geodatabase Design](http://downloads2.esri.com/support/documentation/ao_/Modeling_our_World.pdf)

### Additional Readings

- Map Projection
- Geocoding

## All About QGIS

- [A Gentle Introduction to GIS](https://docs.qgis.org/3.16/en/docs/gentle_gis_introduction/index.html). Chapter 3-9.





