---
title: "Lesson 1: Introduction to GIS for Urban Planning"
description: |
  A new article created using the Distill format.
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Lesson Outline

### Course Overview

- An Overview of Urban Planning
    - Theory and philosophy of planning
    - Practice of urban planning
    - Urban planning and management in Singapore
- Introduction to GIS
    - Basic concept of a GIS
    - System view of a GIS
    - GIS in the context of Smart Nation

## Lesson Slides and Hands-on Notes 

- Lesson slide in [html](lesson/lesson01/lesson01.html) and [pdf](lesson/lesson01/lesson01.pdf) formats
- Hands-on Exercise in [html]() format.


## Readings
### Core Readings

- [Urban Planning](https://www.britannica.com/topic/urban-planning)
- Chapter 2: Re-Examining Singapore's Urban Planning and Governance Framework in [Planning Singapore: The Experimental City](https://www-taylorfrancis-com.libproxy.smu.edu.sg/books/edit/10.4324/9781351058230/planning-singapore-stephen-hamnett-belinda-yuen). This book is available in digital form in smu library.
- [Chapter 6: Geographic Information Systems](https://link-springer-com.libproxy.smu.edu.sg/content/pdf/10.1007%2F978-3-540-72680-7_6.pdf) of Springer Handbook of Geographic Information
- [Chapter 20: Planning](https://link-springer-com.libproxy.smu.edu.sg/content/pdf/10.1007%2F978-3-540-72680-7_20.pdf) of Springer Handbook of Geographic Information
- [How GIS technology helps in Smart City growth?](https://www.youtube.com/watch?v=OuzlMPbx78k)
- [GIS: The Intelligent Nervous System](https://www.esri.com/videos/watch?&channelid=UCJ203R9PsZn6wF_zYfsp1SA&videoid=pg7ByVZo_sg&playlistid=PLaPDDLTCmy4bC2dGacC3ZH8YnCl4x7kuB&See%20What%20Others%20Can%27t)


### Addition Readings

- [What Is GIS?](https://www.esri.com/videos/watch?videoid=LHDCRjAxpI0&title=what-is-gis-)
- [Geographic Information Systems and Urban Planning](https://www.youtube.com/watch?v=G9xNKb4T8ZM)
- [See What Others Can't](https://www.esri.com/videos/watch?&channelid=UCJ203R9PsZn6wF_zYfsp1SA&videoid=pg7ByVZo_sg&playlistid=PLaPDDLTCmy4bC2dGacC3ZH8YnCl4x7kuB&See%20What%20Others%20Can%27t)
- [Urban Planning](https://en.wikipedia.org/wiki/Urban_planning)
- [What is Geographic Information Systems (GIS)?](https://gisgeography.com/what-gis-geographic-information-systems/)
- Shatkin, G (2014) ["Reinterpreting the Meaning of the 'Singapore' Model: State Capitalism and Urban Planning"](https://onlinelibrary-wiley-com.libproxy.smu.edu.sg/doi/full/10.1111/1468-2427.12095), International Journal of Urban and Regional Research, Vol. 38, Issue 1, pp. 116-137.

## All About QGIS

- [2. Introducing GIS](https://docs.qgis.org/3.16/en/docs/gentle_gis_introduction/introducing_gis.html) of **A Gentle Introduction to GIS**.
- [**QGIS User Guide**](https://docs.qgis.org/3.16/en/docs/user_manual/index.html). Chapter 3-9.
- [2. Module: Creating and Exploring a Basic MapQGIS Training Manual](https://docs.qgis.org/3.16/en/docs/training_manual/basic_map/index.html) of **QGIS Training Manual**





