---
title: "Lesson 4: Thematic Mapping and GeoVisualisation"
description: |
  A new article created using the Distill format.
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Content
- Thematic Mapping and Geovisualization
- Qualitative maps: visual variables and cartographic symbols
- Quantitative maps: data scaling, data classification, and principles of colour
- Mapping movement, change, and process
- Map composition and map symbolization
    - Map design
- Map Analysis Techniques
    - Map reading techniques
    - Visualising statistical data

## Readings
### Core Reading (Highly recommended)
- [What is a map?](https://www.axismaps.com/guide/what-is-a-map)
- [Visual Variables](https://www.axismaps.com/guide/visual-variables)
- [Using Colors on Maps](https://www.axismaps.com/guide/using-colors-on-maps)
- [Scale and Generalization](https://www.axismaps.com/guide/scale-and-generalization)
- [Proportional Symbols](https://www.axismaps.com/guide/proportional-symbols)
- [Choropleth Maps](https://www.axismaps.com/guide/choropleth)
- [The Basics of Data Classification](https://www.axismaps.com/guide/data-classification)


### Additional Readings
- [Choropleth Maps – A Guide to Data Classification](https://gisgeography.com/choropleth-maps-data-classification/)
- [Bivariate Choropleth](https://www.axismaps.com/guide/bivariate-choropleth)
- [Value-by-alpha maps](http://andywoodruff.com/blog/value-by-alpha-maps/)
- [What to consider when creating choropleth maps](https://blog.datawrapper.de/choroplethmaps/)
- [Choropleth Mapping with Exploratory Data Analysis](https://www.directionsmag.com/article/3363)
- [Cartogram Maps: Data Visualization with Exaggeration](https://gisgeography.com/cartogram-maps/)
- [Cartogram](https://en.wikipedia.org/wiki/Cartogram)

## References

- Slocum, T., McMaster R., Kessler, F. and Howard, H. (2005) Thematic Cartography and Geographic Visualization (2nd Edition), Prentice Hall, New Jersey.
- Kraak, M-J & Ormeling, F. (2003) (2nd Edition) Cartography: Visualization of Geospatial Data. Pearson Education Limited, Essex, England.
- Monmonier, M. (1996) How to Lie with Maps, The University of Chicago Press, USA.

## QGIS methods

- [The Vector Properties Dialog: Symbology Properties](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/vector_properties.html#symbology-properties)
- [The Vector Properties Dialog: Labels Properties](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/vector_properties.html#labels-properties)
- [The Vector Properties Dialog: Diagrams Properties](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/vector_properties.html#diagrams-properties)
- [14.1.6. Masks Properties](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/vector_properties.html#masks-properties)
- [14.1.7. 3D View Properties](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/vector_properties.html#d-view-properties)
- [14.1.10. Joins Properties](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/vector_properties.html#joins-properties)
- [14.1.13. Display Properties](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/vector_properties.html#display-properties)
- [14.1.14. Rendering Properties](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/vector_properties.html#rendering-properties)
- [14.1.15. Variables Properties](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/vector_properties.html#variables-properties)
- [14.1.18. Legend Properties](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/vector_properties.html#legend-properties)
- [18. Laying out the maps](https://docs.qgis.org/3.16/en/docs/user_manual/print_composer/index.html)









